
KiwiTestEnv = Environment(CPPPATH = ['.', '../src/'])
#KiwiTestEnv.Append(CPPPATH = ['../src/'])
KiwiTestEnv.Append(LIBS = ['Kiwi']) 
KiwiTestEnv.Program(target='test', source=['test.cpp'])
KiwiTestEnv.Program('mpl/TypeListTest.cpp')
KiwiTestEnv.Program('mpl/TypeListTransform2Test.cpp')
KiwiTestEnv.Program('mpl/NumberTest.cpp')
KiwiTestEnv.Program('mpl/ApplyBitwiseOperatorTest.cpp')
KiwiTestEnv.Program('mpl/TupleTest.cpp')
KiwiTestEnv.Program('mpl/MakeContainerTest.cpp')
KiwiTestEnv.Program('mpl/IsRelatedTest.cpp')
KiwiTestEnv.Program('mpl/FillTypeListTest.cpp')

KiwiTestEnv.Program('utils/DebugStreamTest.cpp')

KiwiTestEnv.Program('core/PortTest.cpp')
KiwiTestEnv.Program('core/DynamicPortTest.cpp')
KiwiTestEnv.Program('core/ContainerTest.cpp')
KiwiTestEnv.Program('core/ContainerManagerTest.cpp')

